# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1338559745);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1338559865);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1350979988);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1338559625);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 204800);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20120515091258");
user_pref("browser.startup.homepage_override.mstone", "rv:12.0");
user_pref("browser.tabs.autoHide", true);
user_pref("browser.tabs.onTop", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1365771096494");
user_pref("datareporting.policy.firstRunTime", "1365684696494");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2122);
user_pref("datareporting.sessions.current.main", 26);
user_pref("datareporting.sessions.current.sessionRestored", 2160);
user_pref("datareporting.sessions.current.startTime", "1365684716344");
user_pref("datareporting.sessions.current.totalTime", 10814);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1365684688252,\"a\":2,\"t\":17735,\"c\":true,\"m\":19,\"fp\":502,\"sr\":10052}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.netrunner.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.adblockplus.currentVersion", "2.0.3");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D:2.0.3,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:20.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1365684558000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1363246983000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1363246984000}}},{\"name\":\"app-profile\",\"addons\":{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"/home/netrunner/.mozilla/firefox/xyuzmp9f.prism/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"mtime\":1365680837000}}}]");
user_pref("extensions.lastAppVersion", "20.0");
user_pref("extensions.lastPlatformVersion", "20.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/tabmix");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20130409215104");
user_pref("gecko.mstone", "20.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 2845);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1365684716);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1365931142);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
