# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1338559745);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1338559865);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1350979988);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1338559625);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 204800);
user_pref("browser.migration.version", 8);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20120515091258");
user_pref("browser.startup.homepage_override.mstone", "rv:12.0");
user_pref("browser.tabs.autoHide", true);
user_pref("browser.tabs.onTop", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.netrunner.bookmarksProcessed", true);
user_pref("extensions.adblockplus.currentVersion", "2.0.3");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D:2.0.3,langpack-en-GB%40firefox.mozilla.org:18.0,langpack-en-ZA%40firefox.mozilla.org:18.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1357927865000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1357927866000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1358256025000}}},{\"name\":\"app-profile\",\"addons\":{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"/home/netrunner/.mozilla/firefox/xyuzmp9f.prism/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"mtime\":1358251841000}}}]");
user_pref("extensions.lastAppVersion", "18.0");
user_pref("extensions.lastPlatformVersion", "18.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/tabmix");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20130111132539");
user_pref("gecko.mstone", "18.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 17220);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1358256272);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1358510319);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
